---
abstract: 'Perl extension for writing XML in PYX format.'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-MinWriter
no_index:
  directory:
    - t
    - inc
requires:
  XML::Writer: '0'
resources:
  repository: https://github.com/klaus03/XML-MinWriter.git
version: '0.07'
